### ISSUE TITLE
Filtering recommendations

### ISSUE THREAD

**Issue by amisepa** [LNDG/mMSE#1]
Hi @jkosciessa 

This is actually a question, not an issue. 

I am trying to write my own code to follow the recommendations from your paper (great work thank you!). But I am confused about which filters you used. 
Independent of the unique cases for scale 1 where there is only the highpass, you first say " To implement control over the scale-wise filter direction and to reduce aliasing, we applied either low- [31, 33, 137], high-, **or** band-pass filters at each scale factor."

But in the following sentences, it sounds like you are doing all of them in a sequence (Butterworth lowpass and highpass, and then the Chebyshev bandpass with frequency bounds that I don't understand (i.e., BP = LP +- 0.05*LP). 

So my question is, do you do either 6th Butterworth lowpass+higpass or 4th order Chebyshev type 1 bandpass? Or both?

And why is the lowpass defined by 1/scale*nyquist and not 1/scale*fs?
And why is the passband defined by BP = LP +- 0.05*LP not simply [HP LP]? 

And what do you mean by "10th order Butterworth filters replaced the Chebyshev filters at scales where the passband was larger than 0.5*Nyquist."? Is it referring to the size or the upper bound of the passband here?

I would be very grateful if you could clarify these points.

Thank you very much in advance,

Cedric

**Comment by jkosciessa** [comment]
Hi @amisepa,

thanks for the questions. Parts of the description may have been unclear and I discovered some discrepancies that i describe below.

**_Do you do either 6th Butterworth lowpass+higpass or 4th order Chebyshev type 1 bandpass? Or both?_**

The choice of filter really defines the spectral content that will be available at each scale. Each of the three versions is an independent choice, filters are **NOT** sequentially combined: either the scale-wise signal content is controlled by prior lowpass, highpass, or bandpass application. Which filter is used is controlled by `cfg.filtmethod`. 

https://github.com/LNDG/mMSE/blob/537354cb91c71b1ca63b5440468aece2a19f0c92/ft_entropyanalysis.m#L175

The traditional way would be to no apply a filter at scale 1, and then use some form of lowpass filter (i.e., allowing only slower frequency content) to derive the signal at scales 2+. The option to use high-pass or band-pass filters instead simply allows more flexibility over the scale-wise frequency content.

**_And why is the lowpass defined by 1/scalenyquist and not 1/scalefs?_**

Half of the sampling rate is defined as the upper resolvable frequency at that scale according to the Nyquist theorem. For a Fs=250 Hz time domain signal, the upper resolvable frequency would be 125 Hz at scale 1. Given that we wish to control the frequency content using the filters, it makes sense to define filters directly based on estimable frequencies.

**_And why is the passband defined by BP = LP +- 0.05*LP not simply [HP LP]?_**

Good question. One of the problems is that the range of HP to LP quickly becomes very narrow towards the higher scales. Regulating the passthrough via the scaling (here 0.05) allows more flexibility regarding the pass-band width. There seems to be a **manuscript typo**: similar to what you suggest, the code defines the passband as BP = [LP + 0.05*LP, HP - 0.05*HP].
https://github.com/LNDG/mMSE/blob/537354cb91c71b1ca63b5440468aece2a19f0c92/ft_entropyanalysis.m#L203
https://github.com/LNDG/mMSE/blob/249cd69bd245e8228bb8c7e4140570858b80c912/ft_entropyanalysis.m#L204

Please note that the specific scaling or bandpass solution chosen here is not meant as a definitive parameter choice, it serves more to illustrate the point of how a 'narrowband' entropy calculation may look like.

**_And what do you mean by "10th order Butterworth filters replaced the Chebyshev filters at scales where the passband was larger than 0.5*Nyquist."?_**

I tried to design filters with a large passthrough magnitude at the target frequency and a large attenuation of adjacent frequencies outside the passband. After trying out different filter parameters, I was rather happy with the chosen filter setup (see Figure S4). One thing I noted was that the filter setup would benefit from differences for larger compared with more narrow passbands. When I look at the code now to answer your question, there does seem to be a discrepancy between the filter setup I reported in the methods and what the code does.

First, a factor of 0.5 as reported in the methods doesn't make sense, as that would require a very large passband that would practically never be specified. Indeed it is 0.05, which is a **manuscript typo**. However, I am a bit confused by the selection line in the code, as it seems to do the inverse of what we intended to do and reported: it seems to use Chebyshev filters only for large passbands and the Butterworth for narrow ones. 

https://github.com/LNDG/mMSE/blob/537354cb91c71b1ca63b5440468aece2a19f0c92/ft_entropyanalysis.m#L207

This indeed appears to be a **bug in the bandpass implementation** of the previous mMSE code. The description in the methods (using a Chebyshev filter for very narrow bands) is what provides the filter properties in Figure S4. I just made a new commit (537354cb91c71b1ca63b5440468aece2a19f0c92) to fix this bug.

A general word of caution: The chosen filter and parameter setup was focussed on contrasting a somewhat generic 'narrowband' MSE approach with the traditional downsampling/low-pass filtering approach. In applications, different filters may make sense if one has a particular frequency range of interest in mind. In any case, I would highly recommend to run some additional simulations in the bandpass case, focussing on the intended application.

In any case, thank you for making me clarify these points. I hope these discrepancies didn't cause too much trouble. Let me know if there are any other questions.

**Comment by amisepa** [comment]
Thank you very much for taking the time to clarify these points, that's good to know. That makes much more sense now. Maybe this thread will also be also helpful to others here in the future. That makes much more sense now. 

Except for [LP + 0.05LP, HP - 0.05HP]. This corresponds to an interval from high to low cutoffs. Don't you mean [HP - 0.05HP, LP + 0.05LP] to get a broader interval from lower to higher cutoff? 

I use EEGLAB instead of Fieldtrip and haven't actually tried your plugin yet. I was trying to implement your recommendations on the refined composite multiscale fuzzy entropy on standard deviation (RCMFE_std) from https://datashare.ed.ac.uk/handle/10283/2099
Are you familiar with this one? I am getting weird results after filtering, not sure if it is compatible. I believe there is a downsampling being applied, maybe that's why. I have been working with it without filters so far and like the outputs better than other algorithms available, but don't understand the details and wasn't aware of the limitations you pointed out in your paper until now. Do you know if the filter approach is still valid with that one, or if it is already more protected against spectral contaminations? 

I will probably play more with filters and your Fieldtrip code when I have some time :)

Also, I don't remember why you chose 42 as the max number of scales? Are there recommendations in this regard? I'm interested in low frequencies for a particular analysis and was hoping to go to higher scales than this? Is the file length the limit to this number?
e.g., 200 scales for frequencies down to 0.64 Hz with sample rate of 256 Hz. 

Thank you!

**Comment by jkosciessa** [comment]
**_Except for [LP + 0.05LP, HP - 0.05HP]. This corresponds to an interval from high to low cutoffs. Don't you mean [HP - 0.05HP, LP + 0.05LP] to get a broader interval from lower to higher cutoff?_**

Your specification would indicate the effective bandpass range (in order of increasing frequencies). I specified [lowpass_Hz highpass_Hz]: This interval needs to have an area of overlap - the effective passband - otherwise you would have specified a no-pass-filter. ;) 

Example: We want a passband from 10-12 Hz, then LP = 12, HP = 10 should do the trick: 
- LP filter attenuates content > 12 Hz, and retains content <12 Hz
- HP filter attenuates content <10Hz, and retains content >10 Hz

Practically, the code initially applies a low-pass filter, followed by a subsequent high-pass filter.

https://github.com/LNDG/mMSE/blob/537354cb91c71b1ca63b5440468aece2a19f0c92/ft_entropyanalysis.m#L224

Hope this makes more sense now.

_**Are you familiar with multiscale fuzzy entropy? Do you know if the filter approach is still valid with that one, or if it is already more protected against spectral contaminations?**_

I am unfortunately not very familiar with this particular variant, but from a quick look at methods and outputs, it seems like it also uses a variance scaling (r parameter), also in its global form, i.e., an r parameter defined based on the original time series. In line with this, Fig.2 shows a clear dependence between 1/f slopes and scale-wise entropy: with increasing scale number, entropy estimates for pure white noise decrease, whereas they are more static for 1/f signals. This is very similar to what we observed (see Figure S7A in our PloS CB paper). 

Ultimately, whether any results you obtain suffer from what you call a 'spectral contamination' depends on what you are looking for, and what claims you are trying to make. Differences in aperiodic component can tell you something about the auto-correlative structure of the signal. Depending on what kind of questions you are asking, you just need to be aware that there is high sensitivity to such properties, and that they may differentially reflect on lower and higher 'coarse graining' scales. For example, if you use a global r parameter, your results at higher 'time scales' will not be uniquely a result of the remaining signal at those scales, but also a function of the removed variance due to the definition of repeats based on the variance/STD of the original signal. If you do not want such link, you could simply redefine r at each scale. This is one example of how spectral content can influence scale-wise entropy; depending on what spectral characteristic you would like to control for, other checks may be in order. 

_**Also, I don't remember why you chose 42 as the max number of scales? Are there recommendations in this regard? I'm interested in low frequencies for a particular analysis and was hoping to go to higher scales than this? Is the file length the limit to this number?**_

In short, whether you can estimate entropy depends on how many samples you will have available in your time series (~ epoch duration & sampling rate) following downsampling at the respective scale, and the number of points you use to define a 'pattern' with. Whether such technical minimum requirement gives you stable and meaningful estimates is of course a different, partly empirical, question. 

I will repeat a recent response from my colleague @kloosterman for the time-resolved mMSE version:

"_The timescales you can look at are determined by the size of your sliding window within which you compute MSE. I used scales 1-42 in my paper [Kloosterman et al., eLife, 2021] because I used a window of 0.5 s with 256 Hz EEG data. That is, at scale 1 I had 256/2 =128 samples. Now the pattern length I used was 2, which means one needs at least 2+1 = 3 data points within the window to compare 2-point patterns and 3-point patterns. 128/3 = ca. 42, so scale 42 is the slowest scale I could look at.  Now that is the case if you want time-resolved MSE. If you have 3000 samples and you compute MSE at once over all samples, you could in principle go to scale 1000, but then you will have few estimates to aggregate over. So it depends if you want time-resolved MSE or not. Hope this helps!_"

Best,
Julian

**Comment by amisepa** [comment]
Hi,

Thank you so much for taking the time to provide all this valuable feedback. 

Ok I was just confused about the bandpass cutoffs because I thought that was the input as a bandpass and normally see [highpass lowpass] for the frequency bounds. But since you do lowpass and highpass one after the other, that doesn't make a difference :)

It is much clearer now regarding the scale-dependent vs global r, when to use the filters, and the maximum scale numbers. I am computing it on 2-min of continuous, ECG and EEG signals recorded simultaneously. Trying to see if there are some relationships in entropy data between these two signals, so this quote confirms that I can use much higher scales to capture lower frequencies.

Thank you!

Cedric

**Comment by jkosciessa** [comment]
Glad to hear my comments were helpful. Will close this issue for now, but feel free to reopen or start a new issue if something else comes up. :)

Best,
Julian
